services:
  traefik:
    image: traefik:v3.5
    container_name: app_traefik
    restart: unless-stopped
    env_file:
      - .env.prod
    command:
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik/dynamic.yml:/etc/traefik/dynamic/dynamic.yml:ro
      - letsencrypt:/letsencrypt
    depends_on:
      - frontend

  postgres:
    image: postgres:16
    container_name: app_postgres_prod
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/imadbils/projet_collaboratif-backend:latest
    build:
      context: ./Back
      dockerfile: Dockerfile
    container_name: app_backend_prod
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: ghcr.io/imadbils/projet_collaboratif-frontend:latest
    build:
      context: ./front-web
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: app_frontend_prod
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  pgdata_prod:
  letsencrypt:
