-- CreateEnum
CREATE TYPE "ResourceCategory" AS ENUM ('FOOD', 'CLOTHES', 'TOOLS', 'TRANSPORT', 'HOUSING', 'SERVICES', 'EDUCATION', 'HEALTH', 'SOCIAL_SUPPORT', 'EVENTS', 'COMMUNITY', 'VOLUNTEERING', 'DONATION', 'JOB_HELP', 'CHILDCARE', 'ELDERLY_HELP', 'PETS', 'SPORT', 'CULTURE', 'OTHER');

-- AlterTable
ALTER TABLE "Resources" ADD COLUMN     "category" "ResourceCategory" NOT NULL DEFAULT 'OTHER';
