import { Resource } from "./types";

export const initialResources: Resource[] = [
  {
    id: "res-1",
    title: "Désamorcer une tension familiale en 10 minutes",
    summary:
      "Un guide pratique pour ralentir l’escalade et rouvrir un dialogue apaisé.",
    content: [
      "Quand une tension monte, le premier enjeu n’est pas de convaincre mais de préserver l’espace relationnel. Une pause annoncée clairement peut suffire à changer la suite de l’échange.",
      "Le guide propose un format simple: observer un fait précis, exprimer son ressenti, dire son besoin puis faire une demande courte et concrète.",
      "Cette ressource peut être utilisée seul, en couple parental ou en fratrie comme support avant une discussion plus difficile.",
    ],
    category: "Guide",
    format: "Lecture",
    relation: "Famille",
    access: "public",
    author: "Équipe éditoriale",
    publishedAt: "28 mars 2026",
    publishedTimestamp: 20260328,
    readingTime: 5,
    likes: 48,
    tags: ["famille", "apaisement", "dialogue"],
    commentCount: 1,
    featured: true,
    comments: [
      {
        id: "c-1",
        author: "Nadia",
        message: "Le découpage en quatre étapes est clair et rassurant.",
        createdAt: "Aujourd’hui",
        replies: [
          {
            id: "r-1",
            author: "Modération",
            message: "Merci, c’est exactement l’objectif de cette fiche.",
            createdAt: "Aujourd’hui",
          },
        ],
      },
    ],
  },
  {
    id: "res-2",
    title: "Réparer une amitié après un malentendu",
    summary:
      "Une fiche concrète pour reprendre contact sans nier la blessure.",
    content: [
      "Réparer une amitié demande de reconnaître ce qui a été vécu sans chercher à imposer une version définitive des faits.",
      "La ressource propose trois gestes: reprendre contact sobrement, laisser une marge à l’autre et convenir d’un échange de réparation réaliste.",
      "Elle peut servir de base à une discussion en présence ou à un premier message de reprise de lien.",
    ],
    category: "Fiche pratique",
    format: "Lecture",
    relation: "Amitié",
    access: "public",
    author: "Maison des relations",
    publishedAt: "24 mars 2026",
    publishedTimestamp: 20260324,
    readingTime: 4,
    likes: 31,
    tags: ["amitié", "réparation", "écoute"],
    commentCount: 0,
    featured: true,
    comments: [],
  },
  {
    id: "res-3",
    title: "Charge mentale dans le couple: signaux faibles et ajustements",
    summary:
      "Une ressource réservée aux comptes connectés pour travailler la répartition invisible.",
    content: [
      "La fatigue mentale dans le couple n’apparaît pas seulement dans les disputes. Elle se lit aussi dans la lassitude, l’évitement et la sensation de porter seul l’anticipation.",
      "Le contenu propose une grille de repérage, une conversation type et un mini-rituel hebdomadaire de régulation.",
      "Cette ressource est réservée à l’espace connecté car elle renvoie vers des outils de suivi personnels.",
    ],
    category: "Article",
    format: "Lecture",
    relation: "Couple",
    access: "restricted",
    author: "Collectif couple & parentalité",
    publishedAt: "22 mars 2026",
    publishedTimestamp: 20260322,
    readingTime: 7,
    likes: 52,
    tags: ["couple", "charge mentale", "organisation"],
    commentCount: 0,
    comments: [],
  },
  {
    id: "res-4",
    title: "Jeu de cartes: mieux se parler après une journée difficile",
    summary:
      "Une activité courte à faire à deux ou en petit groupe pour relancer un échange plus doux.",
    content: [
      "Cette activité propose des cartes de questions simples à piocher pour partager un ressenti, une gratitude ou un besoin sans pression.",
      "Le jeu peut être lancé à la maison, entre amis ou dans un cadre associatif. Il vise moins la performance que la qualité de présence.",
      "Le prototype mobile permet de démarrer l’activité, d’inviter des participants et d’échanger quelques messages autour du moment choisi.",
    ],
    category: "Activité / Jeu",
    format: "Activité",
    relation: "Famille",
    access: "public",
    author: "Laboratoire citoyen",
    publishedAt: "20 mars 2026",
    publishedTimestamp: 20260320,
    readingTime: 3,
    likes: 40,
    tags: ["activité", "jeu", "famille"],
    commentCount: 1,
    featured: true,
    comments: [
      {
        id: "c-2",
        author: "Julie",
        message: "Testé avec des adolescents, le format a bien fonctionné.",
        createdAt: "Hier",
        replies: [],
      },
    ],
  },
  {
    id: "res-5",
    title: "Poser une limite au travail sans rompre la coopération",
    summary:
      "Un guide pour rester clair sur son cadre tout en gardant une relation professionnelle stable.",
    content: [
      "Poser une limite, c’est préciser ce qui est faisable, soutenable ou acceptable dans un cadre commun.",
      "Le guide insiste sur trois éléments: rappeler l’objectif partagé, nommer la contrainte et proposer une alternative réaliste.",
      "La répétition calme compte davantage que la fermeté spectaculaire.",
    ],
    category: "Guide",
    format: "Lecture",
    relation: "Travail",
    access: "restricted",
    author: "Cellule prévention",
    publishedAt: "18 mars 2026",
    publishedTimestamp: 20260318,
    readingTime: 6,
    likes: 27,
    tags: ["travail", "limites", "assertivité"],
    commentCount: 0,
    comments: [],
  },
];
